CREATE TABLE public.team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    location TEXT NOT NULL CHECK (location IN ('BLR', 'PUN', 'HYD')),
    career_level INTEGER NOT NULL CHECK (career_level IN (7, 8, 9, 10)),
    primary_skill TEXT NOT NULL,
    secondary_skill TEXT,
    email TEXT NOT NULL,
    phone_number TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);